/*
 * generated by Xtext 2.26.0
 */
package org.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.solution.ui.internal.SolutionActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SolutionExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SolutionActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SolutionActivator activator = SolutionActivator.getInstance();
		return activator != null ? activator.getInjector(SolutionActivator.ORG_XTEXT_SOLUTION) : null;
	}

}
