/*
 * generated by Xtext 2.26.0
 */
package org.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.command.ui.internal.CommandActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CommandExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(CommandActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		CommandActivator activator = CommandActivator.getInstance();
		return activator != null ? activator.getInjector(CommandActivator.ORG_XTEXT_COMMAND) : null;
	}

}
