/**
 * generated by Xtext 2.20.0
 */
package lsi.us.es.mis.xtext.exercise.myDomainModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see lsi.us.es.mis.xtext.exercise.myDomainModel.MyDomainModelPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
