/**
 * generated by Xtext 2.26.0
 */
package org.xtext.operations.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.operations.Conditions;
import org.xtext.operations.Initial;
import org.xtext.operations.NotLaterThan;
import org.xtext.operations.Operation;
import org.xtext.operations.OperationalArm;
import org.xtext.operations.OperationsFactory;
import org.xtext.operations.OperationsPackage;
import org.xtext.operations.Solution;
import org.xtext.operations.angle;
import org.xtext.operations.angle_res;
import org.xtext.operations.isAtOperation;
import org.xtext.operations.isAtSingleOperation;
import org.xtext.operations.result;
import org.xtext.operations.rotateAllServosOperation;
import org.xtext.operations.rotateServoOperation;
import org.xtext.operations.servo;
import org.xtext.operations.time;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class OperationsPackageImpl extends EPackageImpl implements OperationsPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass initialEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass solutionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass conditionsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass operationalArmEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass rotateServoOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass rotateAllServosOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass resultEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass notLaterThanEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass isAtSingleOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass isAtOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass timeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass servoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass angleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass angle_resEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.operations.OperationsPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private OperationsPackageImpl()
  {
    super(eNS_URI, OperationsFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link OperationsPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static OperationsPackage init()
  {
    if (isInited) return (OperationsPackage)EPackage.Registry.INSTANCE.getEPackage(OperationsPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredOperationsPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    OperationsPackageImpl theOperationsPackage = registeredOperationsPackage instanceof OperationsPackageImpl ? (OperationsPackageImpl)registeredOperationsPackage : new OperationsPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theOperationsPackage.createPackageContents();

    // Initialize created meta-data
    theOperationsPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theOperationsPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(OperationsPackage.eNS_URI, theOperationsPackage);
    return theOperationsPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInitial()
  {
    return initialEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperation()
  {
    return operationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getOperation_Name()
  {
    return (EAttribute)operationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getOperation_SEP1()
  {
    return (EAttribute)operationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getOperation_SEP2()
  {
    return (EAttribute)operationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOperation_TIME()
  {
    return (EReference)operationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getOperation_END()
  {
    return (EAttribute)operationEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSolution()
  {
    return solutionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getConditions()
  {
    return conditionsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getConditions_Name()
  {
    return (EAttribute)conditionsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOperationalArm()
  {
    return operationalArmEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getOperationalArm_Name()
  {
    return (EAttribute)operationalArmEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOperationalArm_TIME()
  {
    return (EReference)operationalArmEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getOperationalArm_END()
  {
    return (EAttribute)operationalArmEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getrotateServoOperation()
  {
    return rotateServoOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getrotateServoOperation_SERVO()
  {
    return (EReference)rotateServoOperationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getrotateServoOperation_ANGLE()
  {
    return (EReference)rotateServoOperationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getrotateAllServosOperation()
  {
    return rotateAllServosOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getrotateAllServosOperation_ANGLE1()
  {
    return (EReference)rotateAllServosOperationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getrotateAllServosOperation_ANGLE2()
  {
    return (EReference)rotateAllServosOperationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getrotateAllServosOperation_ANGLE3()
  {
    return (EReference)rotateAllServosOperationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getrotateAllServosOperation_SEP3()
  {
    return (EAttribute)rotateAllServosOperationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getrotateAllServosOperation_ANGLE4()
  {
    return (EReference)rotateAllServosOperationEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getrotateAllServosOperation_SEP4()
  {
    return (EAttribute)rotateAllServosOperationEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getrotateAllServosOperation_ANGLE5()
  {
    return (EReference)rotateAllServosOperationEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getrotateAllServosOperation_SEP5()
  {
    return (EAttribute)rotateAllServosOperationEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getrotateAllServosOperation_ANGLE6()
  {
    return (EReference)rotateAllServosOperationEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getrotateAllServosOperation_SEP6()
  {
    return (EAttribute)rotateAllServosOperationEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getresult()
  {
    return resultEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getresult_Name()
  {
    return (EAttribute)resultEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getresult_TIME()
  {
    return (EReference)resultEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNotLaterThan()
  {
    return notLaterThanEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getNotLaterThan_TIME()
  {
    return (EReference)notLaterThanEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNotLaterThan_SEP()
  {
    return (EAttribute)notLaterThanEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNotLaterThan_QUERY()
  {
    return (EAttribute)notLaterThanEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getisAtSingleOperation()
  {
    return isAtSingleOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getisAtSingleOperation_SERVO()
  {
    return (EReference)isAtSingleOperationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getisAtSingleOperation_SEP1()
  {
    return (EAttribute)isAtSingleOperationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getisAtSingleOperation_ANGLE()
  {
    return (EReference)isAtSingleOperationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getisAtSingleOperation_SEP2()
  {
    return (EAttribute)isAtSingleOperationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getisAtSingleOperation_ANGLE_RES()
  {
    return (EReference)isAtSingleOperationEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getisAtSingleOperation_END()
  {
    return (EAttribute)isAtSingleOperationEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getisAtSingleOperation_VALUE()
  {
    return (EAttribute)isAtSingleOperationEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getisAtOperation()
  {
    return isAtOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getisAtOperation_ANGLE1()
  {
    return (EReference)isAtOperationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getisAtOperation_SEP1()
  {
    return (EAttribute)isAtOperationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getisAtOperation_ANGLE2()
  {
    return (EReference)isAtOperationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getisAtOperation_SEP2()
  {
    return (EAttribute)isAtOperationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getisAtOperation_ANGLE3()
  {
    return (EReference)isAtOperationEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getisAtOperation_SEP3()
  {
    return (EAttribute)isAtOperationEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getisAtOperation_ANGLE4()
  {
    return (EReference)isAtOperationEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getisAtOperation_SEP4()
  {
    return (EAttribute)isAtOperationEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getisAtOperation_ANGLE5()
  {
    return (EReference)isAtOperationEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getisAtOperation_SEP5()
  {
    return (EAttribute)isAtOperationEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getisAtOperation_ANGLE6()
  {
    return (EReference)isAtOperationEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getisAtOperation_SEP6()
  {
    return (EAttribute)isAtOperationEClass.getEStructuralFeatures().get(11);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getisAtOperation_ANGLE_RES()
  {
    return (EReference)isAtOperationEClass.getEStructuralFeatures().get(12);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getisAtOperation_END()
  {
    return (EAttribute)isAtOperationEClass.getEStructuralFeatures().get(13);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getisAtOperation_VALUE()
  {
    return (EAttribute)isAtOperationEClass.getEStructuralFeatures().get(14);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass gettime()
  {
    return timeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute gettime_TIME()
  {
    return (EAttribute)timeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getservo()
  {
    return servoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getservo_SERVO()
  {
    return (EAttribute)servoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getangle()
  {
    return angleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getangle_ANGLE()
  {
    return (EAttribute)angleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getangle_res()
  {
    return angle_resEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getangle_res_ANGLE_RES()
  {
    return (EAttribute)angle_resEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationsFactory getOperationsFactory()
  {
    return (OperationsFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    initialEClass = createEClass(INITIAL);

    operationEClass = createEClass(OPERATION);
    createEAttribute(operationEClass, OPERATION__NAME);
    createEAttribute(operationEClass, OPERATION__SEP1);
    createEAttribute(operationEClass, OPERATION__SEP2);
    createEReference(operationEClass, OPERATION__TIME);
    createEAttribute(operationEClass, OPERATION__END);

    solutionEClass = createEClass(SOLUTION);

    conditionsEClass = createEClass(CONDITIONS);
    createEAttribute(conditionsEClass, CONDITIONS__NAME);

    operationalArmEClass = createEClass(OPERATIONAL_ARM);
    createEAttribute(operationalArmEClass, OPERATIONAL_ARM__NAME);
    createEReference(operationalArmEClass, OPERATIONAL_ARM__TIME);
    createEAttribute(operationalArmEClass, OPERATIONAL_ARM__END);

    rotateServoOperationEClass = createEClass(ROTATE_SERVO_OPERATION);
    createEReference(rotateServoOperationEClass, ROTATE_SERVO_OPERATION__SERVO);
    createEReference(rotateServoOperationEClass, ROTATE_SERVO_OPERATION__ANGLE);

    rotateAllServosOperationEClass = createEClass(ROTATE_ALL_SERVOS_OPERATION);
    createEReference(rotateAllServosOperationEClass, ROTATE_ALL_SERVOS_OPERATION__ANGLE1);
    createEReference(rotateAllServosOperationEClass, ROTATE_ALL_SERVOS_OPERATION__ANGLE2);
    createEReference(rotateAllServosOperationEClass, ROTATE_ALL_SERVOS_OPERATION__ANGLE3);
    createEAttribute(rotateAllServosOperationEClass, ROTATE_ALL_SERVOS_OPERATION__SEP3);
    createEReference(rotateAllServosOperationEClass, ROTATE_ALL_SERVOS_OPERATION__ANGLE4);
    createEAttribute(rotateAllServosOperationEClass, ROTATE_ALL_SERVOS_OPERATION__SEP4);
    createEReference(rotateAllServosOperationEClass, ROTATE_ALL_SERVOS_OPERATION__ANGLE5);
    createEAttribute(rotateAllServosOperationEClass, ROTATE_ALL_SERVOS_OPERATION__SEP5);
    createEReference(rotateAllServosOperationEClass, ROTATE_ALL_SERVOS_OPERATION__ANGLE6);
    createEAttribute(rotateAllServosOperationEClass, ROTATE_ALL_SERVOS_OPERATION__SEP6);

    resultEClass = createEClass(RESULT);
    createEAttribute(resultEClass, RESULT__NAME);
    createEReference(resultEClass, RESULT__TIME);

    notLaterThanEClass = createEClass(NOT_LATER_THAN);
    createEReference(notLaterThanEClass, NOT_LATER_THAN__TIME);
    createEAttribute(notLaterThanEClass, NOT_LATER_THAN__SEP);
    createEAttribute(notLaterThanEClass, NOT_LATER_THAN__QUERY);

    isAtSingleOperationEClass = createEClass(IS_AT_SINGLE_OPERATION);
    createEReference(isAtSingleOperationEClass, IS_AT_SINGLE_OPERATION__SERVO);
    createEAttribute(isAtSingleOperationEClass, IS_AT_SINGLE_OPERATION__SEP1);
    createEReference(isAtSingleOperationEClass, IS_AT_SINGLE_OPERATION__ANGLE);
    createEAttribute(isAtSingleOperationEClass, IS_AT_SINGLE_OPERATION__SEP2);
    createEReference(isAtSingleOperationEClass, IS_AT_SINGLE_OPERATION__ANGLE_RES);
    createEAttribute(isAtSingleOperationEClass, IS_AT_SINGLE_OPERATION__END);
    createEAttribute(isAtSingleOperationEClass, IS_AT_SINGLE_OPERATION__VALUE);

    isAtOperationEClass = createEClass(IS_AT_OPERATION);
    createEReference(isAtOperationEClass, IS_AT_OPERATION__ANGLE1);
    createEAttribute(isAtOperationEClass, IS_AT_OPERATION__SEP1);
    createEReference(isAtOperationEClass, IS_AT_OPERATION__ANGLE2);
    createEAttribute(isAtOperationEClass, IS_AT_OPERATION__SEP2);
    createEReference(isAtOperationEClass, IS_AT_OPERATION__ANGLE3);
    createEAttribute(isAtOperationEClass, IS_AT_OPERATION__SEP3);
    createEReference(isAtOperationEClass, IS_AT_OPERATION__ANGLE4);
    createEAttribute(isAtOperationEClass, IS_AT_OPERATION__SEP4);
    createEReference(isAtOperationEClass, IS_AT_OPERATION__ANGLE5);
    createEAttribute(isAtOperationEClass, IS_AT_OPERATION__SEP5);
    createEReference(isAtOperationEClass, IS_AT_OPERATION__ANGLE6);
    createEAttribute(isAtOperationEClass, IS_AT_OPERATION__SEP6);
    createEReference(isAtOperationEClass, IS_AT_OPERATION__ANGLE_RES);
    createEAttribute(isAtOperationEClass, IS_AT_OPERATION__END);
    createEAttribute(isAtOperationEClass, IS_AT_OPERATION__VALUE);

    timeEClass = createEClass(TIME);
    createEAttribute(timeEClass, TIME__TIME);

    servoEClass = createEClass(SERVO);
    createEAttribute(servoEClass, SERVO__SERVO);

    angleEClass = createEClass(ANGLE);
    createEAttribute(angleEClass, ANGLE__ANGLE);

    angle_resEClass = createEClass(ANGLE_RES);
    createEAttribute(angle_resEClass, ANGLE_RES__ANGLE_RES);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    operationalArmEClass.getESuperTypes().add(this.getInitial());
    rotateServoOperationEClass.getESuperTypes().add(this.getOperation());
    rotateAllServosOperationEClass.getESuperTypes().add(this.getOperation());
    resultEClass.getESuperTypes().add(this.getSolution());
    notLaterThanEClass.getESuperTypes().add(this.getConditions());
    isAtSingleOperationEClass.getESuperTypes().add(this.getConditions());
    isAtOperationEClass.getESuperTypes().add(this.getConditions());

    // Initialize classes and features; add operations and parameters
    initEClass(initialEClass, Initial.class, "Initial", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(operationEClass, Operation.class, "Operation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getOperation_Name(), ecorePackage.getEString(), "name", null, 0, 1, Operation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getOperation_SEP1(), ecorePackage.getEString(), "SEP1", null, 0, 1, Operation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getOperation_SEP2(), ecorePackage.getEString(), "SEP2", null, 0, 1, Operation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getOperation_TIME(), this.gettime(), null, "TIME", null, 0, 1, Operation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getOperation_END(), ecorePackage.getEString(), "END", null, 0, 1, Operation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(solutionEClass, Solution.class, "Solution", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(conditionsEClass, Conditions.class, "Conditions", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getConditions_Name(), ecorePackage.getEString(), "name", null, 0, 1, Conditions.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(operationalArmEClass, OperationalArm.class, "OperationalArm", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getOperationalArm_Name(), ecorePackage.getEString(), "name", null, 0, 1, OperationalArm.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getOperationalArm_TIME(), this.gettime(), null, "TIME", null, 0, 1, OperationalArm.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getOperationalArm_END(), ecorePackage.getEString(), "END", null, 0, 1, OperationalArm.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(rotateServoOperationEClass, rotateServoOperation.class, "rotateServoOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getrotateServoOperation_SERVO(), this.getservo(), null, "SERVO", null, 0, 1, rotateServoOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getrotateServoOperation_ANGLE(), this.getangle(), null, "ANGLE", null, 0, 1, rotateServoOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(rotateAllServosOperationEClass, rotateAllServosOperation.class, "rotateAllServosOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getrotateAllServosOperation_ANGLE1(), this.getangle(), null, "ANGLE1", null, 0, 1, rotateAllServosOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getrotateAllServosOperation_ANGLE2(), this.getangle(), null, "ANGLE2", null, 0, 1, rotateAllServosOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getrotateAllServosOperation_ANGLE3(), this.getangle(), null, "ANGLE3", null, 0, 1, rotateAllServosOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getrotateAllServosOperation_SEP3(), ecorePackage.getEString(), "SEP3", null, 0, 1, rotateAllServosOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getrotateAllServosOperation_ANGLE4(), this.getangle(), null, "ANGLE4", null, 0, 1, rotateAllServosOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getrotateAllServosOperation_SEP4(), ecorePackage.getEString(), "SEP4", null, 0, 1, rotateAllServosOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getrotateAllServosOperation_ANGLE5(), this.getangle(), null, "ANGLE5", null, 0, 1, rotateAllServosOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getrotateAllServosOperation_SEP5(), ecorePackage.getEString(), "SEP5", null, 0, 1, rotateAllServosOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getrotateAllServosOperation_ANGLE6(), this.getangle(), null, "ANGLE6", null, 0, 1, rotateAllServosOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getrotateAllServosOperation_SEP6(), ecorePackage.getEString(), "SEP6", null, 0, 1, rotateAllServosOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(resultEClass, result.class, "result", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getresult_Name(), ecorePackage.getEString(), "name", null, 0, 1, result.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getresult_TIME(), this.gettime(), null, "TIME", null, 0, 1, result.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(notLaterThanEClass, NotLaterThan.class, "NotLaterThan", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getNotLaterThan_TIME(), this.gettime(), null, "TIME", null, 0, 1, NotLaterThan.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getNotLaterThan_SEP(), ecorePackage.getEString(), "SEP", null, 0, 1, NotLaterThan.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getNotLaterThan_QUERY(), ecorePackage.getEString(), "QUERY", null, 0, 1, NotLaterThan.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(isAtSingleOperationEClass, isAtSingleOperation.class, "isAtSingleOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getisAtSingleOperation_SERVO(), this.getservo(), null, "SERVO", null, 0, 1, isAtSingleOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getisAtSingleOperation_SEP1(), ecorePackage.getEString(), "SEP1", null, 0, 1, isAtSingleOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getisAtSingleOperation_ANGLE(), this.getangle(), null, "ANGLE", null, 0, 1, isAtSingleOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getisAtSingleOperation_SEP2(), ecorePackage.getEString(), "SEP2", null, 0, 1, isAtSingleOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getisAtSingleOperation_ANGLE_RES(), this.getangle_res(), null, "ANGLE_RES", null, 0, 1, isAtSingleOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getisAtSingleOperation_END(), ecorePackage.getEString(), "END", null, 0, 1, isAtSingleOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getisAtSingleOperation_VALUE(), ecorePackage.getEString(), "VALUE", null, 0, 1, isAtSingleOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(isAtOperationEClass, isAtOperation.class, "isAtOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getisAtOperation_ANGLE1(), this.getangle(), null, "ANGLE1", null, 0, 1, isAtOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getisAtOperation_SEP1(), ecorePackage.getEString(), "SEP1", null, 0, 1, isAtOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getisAtOperation_ANGLE2(), this.getangle(), null, "ANGLE2", null, 0, 1, isAtOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getisAtOperation_SEP2(), ecorePackage.getEString(), "SEP2", null, 0, 1, isAtOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getisAtOperation_ANGLE3(), this.getangle(), null, "ANGLE3", null, 0, 1, isAtOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getisAtOperation_SEP3(), ecorePackage.getEString(), "SEP3", null, 0, 1, isAtOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getisAtOperation_ANGLE4(), this.getangle(), null, "ANGLE4", null, 0, 1, isAtOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getisAtOperation_SEP4(), ecorePackage.getEString(), "SEP4", null, 0, 1, isAtOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getisAtOperation_ANGLE5(), this.getangle(), null, "ANGLE5", null, 0, 1, isAtOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getisAtOperation_SEP5(), ecorePackage.getEString(), "SEP5", null, 0, 1, isAtOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getisAtOperation_ANGLE6(), this.getangle(), null, "ANGLE6", null, 0, 1, isAtOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getisAtOperation_SEP6(), ecorePackage.getEString(), "SEP6", null, 0, 1, isAtOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getisAtOperation_ANGLE_RES(), this.getangle_res(), null, "ANGLE_RES", null, 0, 1, isAtOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getisAtOperation_END(), ecorePackage.getEString(), "END", null, 0, 1, isAtOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getisAtOperation_VALUE(), ecorePackage.getEString(), "VALUE", null, 0, 1, isAtOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(timeEClass, time.class, "time", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(gettime_TIME(), ecorePackage.getEInt(), "TIME", null, 0, 1, time.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(servoEClass, servo.class, "servo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getservo_SERVO(), ecorePackage.getEInt(), "SERVO", null, 0, 1, servo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(angleEClass, angle.class, "angle", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getangle_ANGLE(), ecorePackage.getEInt(), "ANGLE", null, 0, 1, angle.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(angle_resEClass, angle_res.class, "angle_res", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getangle_res_ANGLE_RES(), ecorePackage.getEInt(), "ANGLE_RES", null, 0, 1, angle_res.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //OperationsPackageImpl
