/**
 * generated by Xtext 2.26.0
 */
package org.xtext.command;

import org.eclipse.emf.common.util.EList;

import org.xtext.solution.Angle;
import org.xtext.solution.Servo;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>rotate Servo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.command.rotateServo#getServo <em>Servo</em>}</li>
 *   <li>{@link org.xtext.command.rotateServo#getAngle <em>Angle</em>}</li>
 * </ul>
 *
 * @see org.xtext.command.CommandPackage#getrotateServo()
 * @model
 * @generated
 */
public interface rotateServo extends Command
{
  /**
   * Returns the value of the '<em><b>Servo</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.solution.Servo}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Servo</em>' containment reference list.
   * @see org.xtext.command.CommandPackage#getrotateServo_Servo()
   * @model containment="true"
   * @generated
   */
  EList<Servo> getServo();

  /**
   * Returns the value of the '<em><b>Angle</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.solution.Angle}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Angle</em>' containment reference list.
   * @see org.xtext.command.CommandPackage#getrotateServo_Angle()
   * @model containment="true"
   * @generated
   */
  EList<Angle> getAngle();

} // rotateServo
