/**
 * generated by Xtext 2.21.0
 */
package lsi.us.es.mis.xtext.myWorldDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Country</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lsi.us.es.mis.xtext.myWorldDsl.Country#getName <em>Name</em>}</li>
 *   <li>{@link lsi.us.es.mis.xtext.myWorldDsl.Country#getArea <em>Area</em>}</li>
 *   <li>{@link lsi.us.es.mis.xtext.myWorldDsl.Country#isPeaceful <em>Peaceful</em>}</li>
 *   <li>{@link lsi.us.es.mis.xtext.myWorldDsl.Country#getPopulation <em>Population</em>}</li>
 *   <li>{@link lsi.us.es.mis.xtext.myWorldDsl.Country#getBorders <em>Borders</em>}</li>
 *   <li>{@link lsi.us.es.mis.xtext.myWorldDsl.Country#getWashedBy <em>Washed By</em>}</li>
 * </ul>
 *
 * @see lsi.us.es.mis.xtext.myWorldDsl.MyWorldDslPackage#getCountry()
 * @model
 * @generated
 */
public interface Country extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see lsi.us.es.mis.xtext.myWorldDsl.MyWorldDslPackage#getCountry_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link lsi.us.es.mis.xtext.myWorldDsl.Country#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Area</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Area</em>' attribute.
   * @see #setArea(String)
   * @see lsi.us.es.mis.xtext.myWorldDsl.MyWorldDslPackage#getCountry_Area()
   * @model
   * @generated
   */
  String getArea();

  /**
   * Sets the value of the '{@link lsi.us.es.mis.xtext.myWorldDsl.Country#getArea <em>Area</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Area</em>' attribute.
   * @see #getArea()
   * @generated
   */
  void setArea(String value);

  /**
   * Returns the value of the '<em><b>Peaceful</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Peaceful</em>' attribute.
   * @see #setPeaceful(boolean)
   * @see lsi.us.es.mis.xtext.myWorldDsl.MyWorldDslPackage#getCountry_Peaceful()
   * @model
   * @generated
   */
  boolean isPeaceful();

  /**
   * Sets the value of the '{@link lsi.us.es.mis.xtext.myWorldDsl.Country#isPeaceful <em>Peaceful</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Peaceful</em>' attribute.
   * @see #isPeaceful()
   * @generated
   */
  void setPeaceful(boolean value);

  /**
   * Returns the value of the '<em><b>Population</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Population</em>' attribute.
   * @see #setPopulation(String)
   * @see lsi.us.es.mis.xtext.myWorldDsl.MyWorldDslPackage#getCountry_Population()
   * @model
   * @generated
   */
  String getPopulation();

  /**
   * Sets the value of the '{@link lsi.us.es.mis.xtext.myWorldDsl.Country#getPopulation <em>Population</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Population</em>' attribute.
   * @see #getPopulation()
   * @generated
   */
  void setPopulation(String value);

  /**
   * Returns the value of the '<em><b>Borders</b></em>' reference list.
   * The list contents are of type {@link lsi.us.es.mis.xtext.myWorldDsl.Country}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Borders</em>' reference list.
   * @see lsi.us.es.mis.xtext.myWorldDsl.MyWorldDslPackage#getCountry_Borders()
   * @model
   * @generated
   */
  EList<Country> getBorders();

  /**
   * Returns the value of the '<em><b>Washed By</b></em>' reference list.
   * The list contents are of type {@link lsi.us.es.mis.xtext.myWorldDsl.Water}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Washed By</em>' reference list.
   * @see lsi.us.es.mis.xtext.myWorldDsl.MyWorldDslPackage#getCountry_WashedBy()
   * @model
   * @generated
   */
  EList<Water> getWashedBy();

} // Country
