/**
 * generated by Xtext 2.21.0
 */
package lsi.us.es.mis.xtext.myWorldDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lake</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see lsi.us.es.mis.xtext.myWorldDsl.MyWorldDslPackage#getLake()
 * @model
 * @generated
 */
public interface Lake extends Water
{
} // Lake
