/*
 * generated by Xtext 2.26.0
 */
package org.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.ide.contentassist.antlr.internal.InternalCPtesterParser;
import org.xtext.services.CPtesterGrammarAccess;

public class CPtesterParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(CPtesterGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, CPtesterGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getCommandAccess().getAlternatives(), "rule__Command__Alternatives");
			builder.put(grammarAccess.getSolutionAccess().getAlternatives(), "rule__Solution__Alternatives");
			builder.put(grammarAccess.getScenarioAccess().getGroup(), "rule__Scenario__Group__0");
			builder.put(grammarAccess.getGivenAccess().getGroup(), "rule__Given__Group__0");
			builder.put(grammarAccess.getAndWhenAccess().getGroup(), "rule__AndWhen__Group__0");
			builder.put(grammarAccess.getWhenAccess().getGroup(), "rule__When__Group__0");
			builder.put(grammarAccess.getThenAccess().getGroup(), "rule__Then__Group__0");
			builder.put(grammarAccess.getAndAccess().getGroup(), "rule__And__Group__0");
			builder.put(grammarAccess.getInitialAccess().getGroup(), "rule__Initial__Group__0");
			builder.put(grammarAccess.getLightRGBOperationAccess().getGroup(), "rule__LightRGBOperation__Group__0");
			builder.put(grammarAccess.getBuzzerOffOperationAccess().getGroup(), "rule__BuzzerOffOperation__Group__0");
			builder.put(grammarAccess.getBuzzerOnOperationAccess().getGroup(), "rule__BuzzerOnOperation__Group__0");
			builder.put(grammarAccess.getCalibrationOperationAccess().getGroup(), "rule__CalibrationOperation__Group__0");
			builder.put(grammarAccess.getCameraColorOperationAccess().getGroup(), "rule__CameraColorOperation__Group__0");
			builder.put(grammarAccess.getReadAllServosOperationAccess().getGroup(), "rule__ReadAllServosOperation__Group__0");
			builder.put(grammarAccess.getReadServoOperationAccess().getGroup(), "rule__ReadServoOperation__Group__0");
			builder.put(grammarAccess.getRotateServoOperationAccess().getGroup(), "rule__RotateServoOperation__Group__0");
			builder.put(grammarAccess.getRotateAllServosOperationAccess().getGroup(), "rule__RotateAllServosOperation__Group__0");
			builder.put(grammarAccess.getResultAccess().getGroup(), "rule__Result__Group__0");
			builder.put(grammarAccess.getConditionsAccess().getGroup(), "rule__Conditions__Group__0");
			builder.put(grammarAccess.getIsAtSingleOperationAccess().getGroup(), "rule__IsAtSingleOperation__Group__0");
			builder.put(grammarAccess.getIsAtOperationAccess().getGroup(), "rule__IsAtOperation__Group__0");
			builder.put(grammarAccess.getScenarioAccess().getSurnameAssignment_1(), "rule__Scenario__SurnameAssignment_1");
			builder.put(grammarAccess.getScenarioAccess().getGivenAssignment_3(), "rule__Scenario__GivenAssignment_3");
			builder.put(grammarAccess.getScenarioAccess().getAndGivenAssignment_4(), "rule__Scenario__AndGivenAssignment_4");
			builder.put(grammarAccess.getScenarioAccess().getWhenAssignment_5(), "rule__Scenario__WhenAssignment_5");
			builder.put(grammarAccess.getScenarioAccess().getThenAssignment_6(), "rule__Scenario__ThenAssignment_6");
			builder.put(grammarAccess.getScenarioAccess().getAndAssignment_7(), "rule__Scenario__AndAssignment_7");
			builder.put(grammarAccess.getGivenAccess().getNameAssignment_0(), "rule__Given__NameAssignment_0");
			builder.put(grammarAccess.getGivenAccess().getInitialAssignment_1(), "rule__Given__InitialAssignment_1");
			builder.put(grammarAccess.getAndWhenAccess().getNameAssignment_0(), "rule__AndWhen__NameAssignment_0");
			builder.put(grammarAccess.getAndWhenAccess().getCommandAssignment_1(), "rule__AndWhen__CommandAssignment_1");
			builder.put(grammarAccess.getWhenAccess().getNameAssignment_0(), "rule__When__NameAssignment_0");
			builder.put(grammarAccess.getWhenAccess().getCommandAssignment_1(), "rule__When__CommandAssignment_1");
			builder.put(grammarAccess.getThenAccess().getNameAssignment_0(), "rule__Then__NameAssignment_0");
			builder.put(grammarAccess.getThenAccess().getResultAssignment_1(), "rule__Then__ResultAssignment_1");
			builder.put(grammarAccess.getAndAccess().getNameAssignment_0(), "rule__And__NameAssignment_0");
			builder.put(grammarAccess.getAndAccess().getConditionsAssignment_1(), "rule__And__ConditionsAssignment_1");
			builder.put(grammarAccess.getAndAccess().getSolutionAssignment_3(), "rule__And__SolutionAssignment_3");
			builder.put(grammarAccess.getInitialAccess().getNameAssignment_0(), "rule__Initial__NameAssignment_0");
			builder.put(grammarAccess.getInitialAccess().getTimeAssignment_2(), "rule__Initial__TimeAssignment_2");
			builder.put(grammarAccess.getLightRGBOperationAccess().getNameAssignment_0(), "rule__LightRGBOperation__NameAssignment_0");
			builder.put(grammarAccess.getLightRGBOperationAccess().getRAssignment_2(), "rule__LightRGBOperation__RAssignment_2");
			builder.put(grammarAccess.getLightRGBOperationAccess().getGAssignment_4(), "rule__LightRGBOperation__GAssignment_4");
			builder.put(grammarAccess.getLightRGBOperationAccess().getBAssignment_6(), "rule__LightRGBOperation__BAssignment_6");
			builder.put(grammarAccess.getBuzzerOffOperationAccess().getNameAssignment_0(), "rule__BuzzerOffOperation__NameAssignment_0");
			builder.put(grammarAccess.getBuzzerOnOperationAccess().getNameAssignment_0(), "rule__BuzzerOnOperation__NameAssignment_0");
			builder.put(grammarAccess.getBuzzerOnOperationAccess().getTimeAssignment_2(), "rule__BuzzerOnOperation__TimeAssignment_2");
			builder.put(grammarAccess.getCalibrationOperationAccess().getNameAssignment_0(), "rule__CalibrationOperation__NameAssignment_0");
			builder.put(grammarAccess.getCalibrationOperationAccess().getColorAssignment_2(), "rule__CalibrationOperation__ColorAssignment_2");
			builder.put(grammarAccess.getCalibrationOperationAccess().getH_minAssignment_4(), "rule__CalibrationOperation__H_minAssignment_4");
			builder.put(grammarAccess.getCalibrationOperationAccess().getS_minAssignment_6(), "rule__CalibrationOperation__S_minAssignment_6");
			builder.put(grammarAccess.getCalibrationOperationAccess().getV_minAssignment_8(), "rule__CalibrationOperation__V_minAssignment_8");
			builder.put(grammarAccess.getCalibrationOperationAccess().getH_maxAssignment_10(), "rule__CalibrationOperation__H_maxAssignment_10");
			builder.put(grammarAccess.getCalibrationOperationAccess().getS_maxAssignment_12(), "rule__CalibrationOperation__S_maxAssignment_12");
			builder.put(grammarAccess.getCalibrationOperationAccess().getV_maxAssignment_14(), "rule__CalibrationOperation__V_maxAssignment_14");
			builder.put(grammarAccess.getCameraColorOperationAccess().getNameAssignment_0(), "rule__CameraColorOperation__NameAssignment_0");
			builder.put(grammarAccess.getCameraColorOperationAccess().getTimeAssignment_2(), "rule__CameraColorOperation__TimeAssignment_2");
			builder.put(grammarAccess.getReadAllServosOperationAccess().getNameAssignment_0(), "rule__ReadAllServosOperation__NameAssignment_0");
			builder.put(grammarAccess.getReadServoOperationAccess().getNameAssignment_0(), "rule__ReadServoOperation__NameAssignment_0");
			builder.put(grammarAccess.getReadServoOperationAccess().getServoAssignment_2(), "rule__ReadServoOperation__ServoAssignment_2");
			builder.put(grammarAccess.getRotateServoOperationAccess().getNameAssignment_0(), "rule__RotateServoOperation__NameAssignment_0");
			builder.put(grammarAccess.getRotateServoOperationAccess().getServoAssignment_2(), "rule__RotateServoOperation__ServoAssignment_2");
			builder.put(grammarAccess.getRotateServoOperationAccess().getAngleAssignment_4(), "rule__RotateServoOperation__AngleAssignment_4");
			builder.put(grammarAccess.getRotateServoOperationAccess().getTimeAssignment_6(), "rule__RotateServoOperation__TimeAssignment_6");
			builder.put(grammarAccess.getRotateAllServosOperationAccess().getNameAssignment_0(), "rule__RotateAllServosOperation__NameAssignment_0");
			builder.put(grammarAccess.getRotateAllServosOperationAccess().getAngle1Assignment_2(), "rule__RotateAllServosOperation__Angle1Assignment_2");
			builder.put(grammarAccess.getRotateAllServosOperationAccess().getAngle2Assignment_4(), "rule__RotateAllServosOperation__Angle2Assignment_4");
			builder.put(grammarAccess.getRotateAllServosOperationAccess().getAngle3Assignment_6(), "rule__RotateAllServosOperation__Angle3Assignment_6");
			builder.put(grammarAccess.getRotateAllServosOperationAccess().getAngle4Assignment_8(), "rule__RotateAllServosOperation__Angle4Assignment_8");
			builder.put(grammarAccess.getRotateAllServosOperationAccess().getAngle5Assignment_10(), "rule__RotateAllServosOperation__Angle5Assignment_10");
			builder.put(grammarAccess.getRotateAllServosOperationAccess().getAngle6Assignment_12(), "rule__RotateAllServosOperation__Angle6Assignment_12");
			builder.put(grammarAccess.getRotateAllServosOperationAccess().getTimeAssignment_14(), "rule__RotateAllServosOperation__TimeAssignment_14");
			builder.put(grammarAccess.getResultAccess().getNameAssignment_0(), "rule__Result__NameAssignment_0");
			builder.put(grammarAccess.getResultAccess().getTimeAssignment_2(), "rule__Result__TimeAssignment_2");
			builder.put(grammarAccess.getConditionsAccess().getNameAssignment_0(), "rule__Conditions__NameAssignment_0");
			builder.put(grammarAccess.getConditionsAccess().getTimeAssignment_2(), "rule__Conditions__TimeAssignment_2");
			builder.put(grammarAccess.getIsAtSingleOperationAccess().getNameAssignment_0(), "rule__IsAtSingleOperation__NameAssignment_0");
			builder.put(grammarAccess.getIsAtSingleOperationAccess().getServoAssignment_2(), "rule__IsAtSingleOperation__ServoAssignment_2");
			builder.put(grammarAccess.getIsAtSingleOperationAccess().getAngleAssignment_4(), "rule__IsAtSingleOperation__AngleAssignment_4");
			builder.put(grammarAccess.getIsAtSingleOperationAccess().getAngle_resAssignment_6(), "rule__IsAtSingleOperation__Angle_resAssignment_6");
			builder.put(grammarAccess.getIsAtOperationAccess().getNameAssignment_0(), "rule__IsAtOperation__NameAssignment_0");
			builder.put(grammarAccess.getIsAtOperationAccess().getAngle1Assignment_2(), "rule__IsAtOperation__Angle1Assignment_2");
			builder.put(grammarAccess.getIsAtOperationAccess().getAngle2Assignment_4(), "rule__IsAtOperation__Angle2Assignment_4");
			builder.put(grammarAccess.getIsAtOperationAccess().getAngle3Assignment_6(), "rule__IsAtOperation__Angle3Assignment_6");
			builder.put(grammarAccess.getIsAtOperationAccess().getAngle4Assignment_8(), "rule__IsAtOperation__Angle4Assignment_8");
			builder.put(grammarAccess.getIsAtOperationAccess().getAngle5Assignment_10(), "rule__IsAtOperation__Angle5Assignment_10");
			builder.put(grammarAccess.getIsAtOperationAccess().getAngle6Assignment_12(), "rule__IsAtOperation__Angle6Assignment_12");
			builder.put(grammarAccess.getIsAtOperationAccess().getAngle_resAssignment_14(), "rule__IsAtOperation__Angle_resAssignment_14");
			builder.put(grammarAccess.getAngle_resAccess().getAngle_resAssignment(), "rule__Angle_res__Angle_resAssignment");
			builder.put(grammarAccess.getAngleAccess().getAngleAssignment(), "rule__Angle__AngleAssignment");
			builder.put(grammarAccess.getTimeAccess().getTimeAssignment(), "rule__Time__TimeAssignment");
			builder.put(grammarAccess.getServoAccess().getServoAssignment(), "rule__Servo__ServoAssignment");
			builder.put(grammarAccess.getV_maxAccess().getV_maxAssignment(), "rule__V_max__V_maxAssignment");
			builder.put(grammarAccess.getS_maxAccess().getS_maxAssignment(), "rule__S_max__S_maxAssignment");
			builder.put(grammarAccess.getH_maxAccess().getH_maxAssignment(), "rule__H_max__H_maxAssignment");
			builder.put(grammarAccess.getV_minAccess().getV_minAssignment(), "rule__V_min__V_minAssignment");
			builder.put(grammarAccess.getS_minAccess().getS_minAssignment(), "rule__S_min__S_minAssignment");
			builder.put(grammarAccess.getH_minAccess().getH_minAssignment(), "rule__H_min__H_minAssignment");
			builder.put(grammarAccess.getColorAccess().getColorAssignment(), "rule__Color__ColorAssignment");
			builder.put(grammarAccess.getBAccess().getBAssignment(), "rule__B__BAssignment");
			builder.put(grammarAccess.getGAccess().getGAssignment(), "rule__G__GAssignment");
			builder.put(grammarAccess.getRAccess().getRAssignment(), "rule__R__RAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private CPtesterGrammarAccess grammarAccess;

	@Override
	protected InternalCPtesterParser createParser() {
		InternalCPtesterParser result = new InternalCPtesterParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public CPtesterGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CPtesterGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
