/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mydsl.B.ui.internal.BActivator;

public class MyDslBUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return BActivator.getInstance().getInjector("org.xtext.example.mydsl.MyDslB");
	}

}
