/**
 * generated by Xtext 2.26.0
 */
package org.xtext.pruebaOperation;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>rotate All Servos</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.pruebaOperation.rotateAllServos#getAngle1 <em>Angle1</em>}</li>
 *   <li>{@link org.xtext.pruebaOperation.rotateAllServos#getAngle2 <em>Angle2</em>}</li>
 *   <li>{@link org.xtext.pruebaOperation.rotateAllServos#getAngle3 <em>Angle3</em>}</li>
 *   <li>{@link org.xtext.pruebaOperation.rotateAllServos#getAngle4 <em>Angle4</em>}</li>
 *   <li>{@link org.xtext.pruebaOperation.rotateAllServos#getAngle5 <em>Angle5</em>}</li>
 *   <li>{@link org.xtext.pruebaOperation.rotateAllServos#getAngle6 <em>Angle6</em>}</li>
 * </ul>
 *
 * @see org.xtext.pruebaOperation.PruebaOperationPackage#getrotateAllServos()
 * @model
 * @generated
 */
public interface rotateAllServos extends Command
{
  /**
   * Returns the value of the '<em><b>Angle1</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.pruebaOperation.Angle}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Angle1</em>' containment reference list.
   * @see org.xtext.pruebaOperation.PruebaOperationPackage#getrotateAllServos_Angle1()
   * @model containment="true"
   * @generated
   */
  EList<Angle> getAngle1();

  /**
   * Returns the value of the '<em><b>Angle2</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.pruebaOperation.Angle}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Angle2</em>' containment reference list.
   * @see org.xtext.pruebaOperation.PruebaOperationPackage#getrotateAllServos_Angle2()
   * @model containment="true"
   * @generated
   */
  EList<Angle> getAngle2();

  /**
   * Returns the value of the '<em><b>Angle3</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.pruebaOperation.Angle}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Angle3</em>' containment reference list.
   * @see org.xtext.pruebaOperation.PruebaOperationPackage#getrotateAllServos_Angle3()
   * @model containment="true"
   * @generated
   */
  EList<Angle> getAngle3();

  /**
   * Returns the value of the '<em><b>Angle4</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.pruebaOperation.Angle}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Angle4</em>' containment reference list.
   * @see org.xtext.pruebaOperation.PruebaOperationPackage#getrotateAllServos_Angle4()
   * @model containment="true"
   * @generated
   */
  EList<Angle> getAngle4();

  /**
   * Returns the value of the '<em><b>Angle5</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.pruebaOperation.Angle}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Angle5</em>' containment reference list.
   * @see org.xtext.pruebaOperation.PruebaOperationPackage#getrotateAllServos_Angle5()
   * @model containment="true"
   * @generated
   */
  EList<Angle> getAngle5();

  /**
   * Returns the value of the '<em><b>Angle6</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.pruebaOperation.Angle}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Angle6</em>' containment reference list.
   * @see org.xtext.pruebaOperation.PruebaOperationPackage#getrotateAllServos_Angle6()
   * @model containment="true"
   * @generated
   */
  EList<Angle> getAngle6();

} // rotateAllServos
