/*
 * generated by Xtext 2.26.0
 */
package org.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.parser.antlr.internal.InternalDofbotDSLParser;
import org.xtext.services.DofbotDSLGrammarAccess;

public class DofbotDSLParser extends AbstractAntlrParser {

	@Inject
	private DofbotDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDofbotDSLParser createParser(XtextTokenStream stream) {
		return new InternalDofbotDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Arm";
	}

	public DofbotDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DofbotDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
