/**
 * generated by Xtext 2.21.0
 */
package lsi.us.es.mis.xtext.myFamilyDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Family</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lsi.us.es.mis.xtext.myFamilyDsl.Family#getSurname <em>Surname</em>}</li>
 *   <li>{@link lsi.us.es.mis.xtext.myFamilyDsl.Family#getPersons <em>Persons</em>}</li>
 * </ul>
 *
 * @see lsi.us.es.mis.xtext.myFamilyDsl.MyFamilyDslPackage#getFamily()
 * @model
 * @generated
 */
public interface Family extends EObject
{
  /**
   * Returns the value of the '<em><b>Surname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Surname</em>' attribute.
   * @see #setSurname(String)
   * @see lsi.us.es.mis.xtext.myFamilyDsl.MyFamilyDslPackage#getFamily_Surname()
   * @model
   * @generated
   */
  String getSurname();

  /**
   * Sets the value of the '{@link lsi.us.es.mis.xtext.myFamilyDsl.Family#getSurname <em>Surname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Surname</em>' attribute.
   * @see #getSurname()
   * @generated
   */
  void setSurname(String value);

  /**
   * Returns the value of the '<em><b>Persons</b></em>' containment reference list.
   * The list contents are of type {@link lsi.us.es.mis.xtext.myFamilyDsl.Person}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Persons</em>' containment reference list.
   * @see lsi.us.es.mis.xtext.myFamilyDsl.MyFamilyDslPackage#getFamily_Persons()
   * @model containment="true"
   * @generated
   */
  EList<Person> getPersons();

} // Family
