/**
 * generated by Xtext 2.21.0
 */
package lsi.us.es.mis.xtext.myFamilyDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see lsi.us.es.mis.xtext.myFamilyDsl.MyFamilyDslPackage
 * @generated
 */
public interface MyFamilyDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyFamilyDslFactory eINSTANCE = lsi.us.es.mis.xtext.myFamilyDsl.impl.MyFamilyDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Family</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Family</em>'.
   * @generated
   */
  Family createFamily();

  /**
   * Returns a new object of class '<em>Person</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Person</em>'.
   * @generated
   */
  Person createPerson();

  /**
   * Returns a new object of class '<em>Man</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Man</em>'.
   * @generated
   */
  Man createMan();

  /**
   * Returns a new object of class '<em>Woman</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Woman</em>'.
   * @generated
   */
  Woman createWoman();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MyFamilyDslPackage getMyFamilyDslPackage();

} //MyFamilyDslFactory
