/*
 * generated by Xtext 2.20.0
 */
package lsi.us.es.mis.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyWorldDslUiModule extends AbstractMyWorldDslUiModule {

	public MyWorldDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
