/**
 * generated by Xtext 2.26.0
 */
package org.xtext.cPTester;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scenario</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.cPTester.Scenario#getSurname <em>Surname</em>}</li>
 *   <li>{@link org.xtext.cPTester.Scenario#getOperations <em>Operations</em>}</li>
 * </ul>
 *
 * @see org.xtext.cPTester.CPTesterPackage#getScenario()
 * @model
 * @generated
 */
public interface Scenario extends EObject
{
  /**
   * Returns the value of the '<em><b>Surname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Surname</em>' attribute.
   * @see #setSurname(String)
   * @see org.xtext.cPTester.CPTesterPackage#getScenario_Surname()
   * @model
   * @generated
   */
  String getSurname();

  /**
   * Sets the value of the '{@link org.xtext.cPTester.Scenario#getSurname <em>Surname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Surname</em>' attribute.
   * @see #getSurname()
   * @generated
   */
  void setSurname(String value);

  /**
   * Returns the value of the '<em><b>Operations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.cPTester.Operation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operations</em>' containment reference list.
   * @see org.xtext.cPTester.CPTesterPackage#getScenario_Operations()
   * @model containment="true"
   * @generated
   */
  EList<Operation> getOperations();

} // Scenario
