<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="world" nsURI="http://www.lsi.us.es/world" nsPrefix="world">
  <eClassifiers xsi:type="ecore:EClass" name="World">
    <eStructuralFeatures xsi:type="ecore:EReference" name="spaces" lowerBound="1"
        upperBound="-1" eType="#//Space" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Continent" eSuperTypes="#//Space">
    <eStructuralFeatures xsi:type="ecore:EReference" name="countries" lowerBound="1"
        upperBound="-1" eType="#//Country" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Water" abstract="true" eSuperTypes="#//Space">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Space" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="area" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Country" eSuperTypes="#//Space">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="population" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="peaceful" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="washedBy" upperBound="-1"
        eType="#//Water"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="borders" upperBound="-1"
        eType="#//Country"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ocean" eSuperTypes="#//Water"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lake" eSuperTypes="#//Water"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sea" eSuperTypes="#//Water"/>
</ecore:EPackage>
