/**
 * generated by Xtext 2.26.0
 */
package org.xtext.dofbotDSL.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.dofbotDSL.Angles;
import org.xtext.dofbotDSL.DofbotDSLPackage;
import org.xtext.dofbotDSL.RotateSingle;
import org.xtext.dofbotDSL.Servos;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rotate Single</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dofbotDSL.impl.RotateSingleImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.dofbotDSL.impl.RotateSingleImpl#getServo <em>Servo</em>}</li>
 *   <li>{@link org.xtext.dofbotDSL.impl.RotateSingleImpl#getAngle <em>Angle</em>}</li>
 *   <li>{@link org.xtext.dofbotDSL.impl.RotateSingleImpl#getTime <em>Time</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RotateSingleImpl extends MinimalEObjectImpl.Container implements RotateSingle
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getServo() <em>Servo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getServo()
   * @generated
   * @ordered
   */
  protected Servos servo;

  /**
   * The cached value of the '{@link #getAngle() <em>Angle</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAngle()
   * @generated
   * @ordered
   */
  protected Angles angle;

  /**
   * The default value of the '{@link #getTime() <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTime()
   * @generated
   * @ordered
   */
  protected static final int TIME_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTime() <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTime()
   * @generated
   * @ordered
   */
  protected int time = TIME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RotateSingleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DofbotDSLPackage.Literals.ROTATE_SINGLE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DofbotDSLPackage.ROTATE_SINGLE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Servos getServo()
  {
    return servo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetServo(Servos newServo, NotificationChain msgs)
  {
    Servos oldServo = servo;
    servo = newServo;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DofbotDSLPackage.ROTATE_SINGLE__SERVO, oldServo, newServo);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setServo(Servos newServo)
  {
    if (newServo != servo)
    {
      NotificationChain msgs = null;
      if (servo != null)
        msgs = ((InternalEObject)servo).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DofbotDSLPackage.ROTATE_SINGLE__SERVO, null, msgs);
      if (newServo != null)
        msgs = ((InternalEObject)newServo).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DofbotDSLPackage.ROTATE_SINGLE__SERVO, null, msgs);
      msgs = basicSetServo(newServo, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DofbotDSLPackage.ROTATE_SINGLE__SERVO, newServo, newServo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Angles getAngle()
  {
    return angle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAngle(Angles newAngle, NotificationChain msgs)
  {
    Angles oldAngle = angle;
    angle = newAngle;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DofbotDSLPackage.ROTATE_SINGLE__ANGLE, oldAngle, newAngle);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAngle(Angles newAngle)
  {
    if (newAngle != angle)
    {
      NotificationChain msgs = null;
      if (angle != null)
        msgs = ((InternalEObject)angle).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DofbotDSLPackage.ROTATE_SINGLE__ANGLE, null, msgs);
      if (newAngle != null)
        msgs = ((InternalEObject)newAngle).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DofbotDSLPackage.ROTATE_SINGLE__ANGLE, null, msgs);
      msgs = basicSetAngle(newAngle, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DofbotDSLPackage.ROTATE_SINGLE__ANGLE, newAngle, newAngle));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getTime()
  {
    return time;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTime(int newTime)
  {
    int oldTime = time;
    time = newTime;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DofbotDSLPackage.ROTATE_SINGLE__TIME, oldTime, time));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DofbotDSLPackage.ROTATE_SINGLE__SERVO:
        return basicSetServo(null, msgs);
      case DofbotDSLPackage.ROTATE_SINGLE__ANGLE:
        return basicSetAngle(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DofbotDSLPackage.ROTATE_SINGLE__NAME:
        return getName();
      case DofbotDSLPackage.ROTATE_SINGLE__SERVO:
        return getServo();
      case DofbotDSLPackage.ROTATE_SINGLE__ANGLE:
        return getAngle();
      case DofbotDSLPackage.ROTATE_SINGLE__TIME:
        return getTime();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DofbotDSLPackage.ROTATE_SINGLE__NAME:
        setName((String)newValue);
        return;
      case DofbotDSLPackage.ROTATE_SINGLE__SERVO:
        setServo((Servos)newValue);
        return;
      case DofbotDSLPackage.ROTATE_SINGLE__ANGLE:
        setAngle((Angles)newValue);
        return;
      case DofbotDSLPackage.ROTATE_SINGLE__TIME:
        setTime((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DofbotDSLPackage.ROTATE_SINGLE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case DofbotDSLPackage.ROTATE_SINGLE__SERVO:
        setServo((Servos)null);
        return;
      case DofbotDSLPackage.ROTATE_SINGLE__ANGLE:
        setAngle((Angles)null);
        return;
      case DofbotDSLPackage.ROTATE_SINGLE__TIME:
        setTime(TIME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DofbotDSLPackage.ROTATE_SINGLE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case DofbotDSLPackage.ROTATE_SINGLE__SERVO:
        return servo != null;
      case DofbotDSLPackage.ROTATE_SINGLE__ANGLE:
        return angle != null;
      case DofbotDSLPackage.ROTATE_SINGLE__TIME:
        return time != TIME_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", time: ");
    result.append(time);
    result.append(')');
    return result.toString();
  }

} //RotateSingleImpl
