/**
 * generated by Xtext 2.26.0
 */
package org.xtext.operations;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>is At</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.operations.OperationsPackage#getisAt()
 * @model
 * @generated
 */
public interface isAt extends Solution
{
} // isAt
