/**
 * generated by Xtext 2.26.0
 */
package org.xtext.operations;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Solution</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.operations.OperationsPackage#getSolution()
 * @model
 * @generated
 */
public interface Solution extends EObject
{
} // Solution
