/*
 * generated by Xtext 2.26.0
 */
package org.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.parser.antlr.internal.InternalPruebaOperationParser;
import org.xtext.services.PruebaOperationGrammarAccess;

public class PruebaOperationParser extends AbstractAntlrParser {

	@Inject
	private PruebaOperationGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPruebaOperationParser createParser(XtextTokenStream stream) {
		return new InternalPruebaOperationParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Initial";
	}

	public PruebaOperationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PruebaOperationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
